version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: bootstrap
    ldflags:
      - -s -w

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}-{{ .Tag }}-
      {{- if eq .Os "linux" }}{{ .Os }}-{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}{{ end }}
      {{- if eq .Os "windows" }}{{ .Os }}-{{ if eq .Arch "amd64" }}AMD64{{ else }}{{ .Arch }}{{ end }}.exe{{ end }}

upx:
  - enabled: true
    compress: "1"
    lzma: false
    brute: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'