name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows 
            goarch: amd64
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@8dbc9990292b456ae78e728c7cf7b857b821faac
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: bootstrap
          executable_compression: "upx -1"
